default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: gaurav
  password: gaurav

development:
  <<: *default
  database: top_ranking_api_development

test:
  <<: *default
  database: top_ranking_api_test

production:
  <<: *default
  database: omdb_production
  username: omdb
  password: <%= ENV['OMDB_DATABASE_PASSWORD'] %>

